server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leavesystem?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20011213fyh
mybatis-plus:
  mapper-locations: classpath*:com/jxd/leave/dao/mapping/*.xml
  type-aliases-package: com.jxd.leave.model
file:
  path: upload/**
  address: /upload/

